version: "3"

networks:
  mgmt:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.52.0/24

services:
  adguard:
    image: adguard/adguardhome
    volumes:
       - ./data/workdir:/opt/adguardhome/work
       - ./data/confdir:/opt/adguardhome/conf
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 67:67/udp
      - 68:68/udp
      - 8083:80/tcp
      - 4443:443/tcp
      - 853:853/tcp
      - 853:853/udp
      - 3000:3000/tcp
      - 8853:8853/udp 
      - 5443:5443/tcp
      - 5443:5443/udp
    restart: unless-stopped
    networks:
      mgmt:
        ipv4_address: 192.168.52.10
# UNCOMMENT THIS IF YOU WANT TO ADMINISTRATE THE ADGUARD VIA THE GUI FORM AN DOCKER INTERNAL VPN CONNECTION
# THE CERTIFICATES ARE IN THE data/wireguard/appdata/config directory
#  vpn:
#    image: lscr.io/linuxserver/wireguard:latest
#    cap_add:
#      - NET_ADMIN
#      - SYS_MODULE
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Africa/Abidjan
#      - SERVERURL=${SERVERURL} #optional
#      - SERVERPORT=${VPN_PORT} #optional
#      - PEERS=5 #optional
#      - PEERDNS=auto #optional
#       - INTERNAL_SUBNET=9.13.13.0 #optional
#      - ALLOWEDIPS=192.168.52.0/24 #optional
#      - LOG_CONFS=true #optional
#    volumes:
#      - ~/data/wireguard/appdata/config:/config
#      - ~/data/wireguard/lib/modules:/lib/modules
#    ports:
#      - ${VPN_PORT}:51820/udp
 #   sysctls:
#      - net.ipv4.conf.all.src_valid_mark=1
#    restart: unless-stopped
#    networks:
#      mgmt:
#        ipv4_address: 192.168.52.2
